name: CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Fetch latest changes
        run: cd ../../../../etymomap/larynx && git fetch origin master && git reset --hard origin/master

      - name: Verify build
        run: cd ../../../../etymomap/larynx && go build .
